### ISSUE TITLE
=)

### ISSUE THREAD

**Issue by max107** [tsukasa-mixer/Orm#1]

**Comment by tsukasa-mixer** [comment]
@max107  Да. это оно. 
если не против)

**Comment by tsukasa-mixer** [comment]
Буду считать что не против )

**Comment by max107** [comment]
Мог бы основной развивать

**Comment by max107** [comment]
Форк в 1 лицо тяжело тянуть. А там уже бандл для работы с symfony и покрытие тестами.

**Comment by tsukasa-mixer** [comment]
@max107 знаю, просто сильно в сторону пришлось отойти.
пока это выложил сюда чтобы просто не проебывать.
